### ISSUE TITLE
Product search return [false]

### ISSUE THREAD

**Issue by ghost** [Productspec/ps-api-docs#1]
Hi,

I just noticed that the search product is not working.

this was working last week.

not sure what happen but it just return false.

Regards

**Comment by CodeNoir** [comment]
We are looking into this now.  Which company are you from?

Cheers

**Comment by onlinesid** [comment]
Hi Chad,

Sid here from Alpha ... @3misyl is one of our team member :)

**Comment by camilord** [comment]
@3misyl @onlinesid and me are from AlphaOne :)

**Comment by CodeNoir** [comment]
@3misyl @onlinesid @camilord the issue with the API should be fixed.  Please let me know if you have any further issues. 👍 😄

**Comment by ghost** [comment]
I did checked the API and Its working well now Thanks .. @onlinesid @camilord  @CodeNoir
